---
- name: Set up Kubernetes dependencies
  import_playbook: k8s_dependencies_setup.yml

- name: Build Kubernetes environment
  import_playbook: k8s_build_setup.yml

- name: Configure Kubernetes post-build settings
  import_playbook: k8s_post_build_configs.yml
# - name: Install Helm applications on Kubernetes
#   import_playbook: k8s_helm_apps.yml
