---
- name: Ensure known_hosts is clean and updated
  hosts: localhost
  gather_facts: false
  vars_files:
      - secrets_computers_setup.yml
  tasks:
      - name: Remove existing SSH key from known_hosts (if present)
        ansible.builtin.shell: ssh-keygen -R {{ item }} || true
        args:
            executable: /bin/bash
        loop: "{{ groups[target_group] }}"

      - name: Add current host key to known_hosts
        ansible.builtin.shell: ssh-keyscan {{ item }} >> ~/.ssh/known_hosts
        args:
            executable: /bin/bash
        loop: "{{ groups[target_group] }}"

- name: Setup SSH Keys for login
  hosts: all
  vars_files:
      - secrets_computers_setup.yml
  tasks:
      - name: Set SSH public key for user {{ ansible_user }}
        ansible.posix.authorized_key:
            user: "{{ ansible_user }}"
            state: present
            key: "{{ lookup('file', '~/.ssh/id_rsa.pub') }}"
